### ISSUE TITLE
Extract Formatting

### ISSUE THREAD

**Issue by ujjvlh** [shreevatsa/pdf-glyph-mapping#9]
Bold (can be got from font name) and Italic.

**Comment by shreevatsa** [comment]
Good idea, though it will be a while before I get to this… please remind me in three weeks if I've not replied again here by then. :-)

Are there italics on any page in the unabridged PDF we were looking at? Because I'd have thought that if so, like regular and bold, there would also be an italic font in the PDF.

**Comment by ujjvlh** [comment]
> Are there italics on any page in the unabridged PDF we were looking at? Because I'd have thought that if so, like regular and bold, there would also be an italic font in the PDF.

All the sentences ending in _उवाच_, mentioning the speaker of the following verses. And the Hindi endings of _adhyāyas_. Are you sure that a separate font needs to be included, that faux italic (or bold) is not produced by the PDF rendering program?

**Comment by shreevatsa** [comment]
Ah ok, I hadn't noticed the italics... If there are then yes it must be as
you say (without using a separate font). I'll take a look sometime.

**Comment by shreevatsa** [comment]
Just noting here for future recall. I looked at only one example, but it appears that the faux-italic formatting is (can be) achieved (in that example PDF) using `Tm`: this is the text matrix, specifying the affine transformation used. That is, an operation like

```
a b c d e f Tm
```

means to calculate actual coordinates `[x', y', 1]` as

```
                        [a   b   0]
[x', y', 1] = [x, y, 1] [c   d   0]
                        [e   f   1]
```

or in other words `(x', y')` is `(ax + cy + e, bx + dy + f)`.

For example, most `BT … ET` fragments may start with something like:

```
1 0 0 -1 77.2656 973 Tm
```

which simply means 

```
x' = x + 77.2656
y = 973 - y
```

From this I guess that individual character glyphs use typical Cartesian coordinates (origin at bottom-left, y increasing upwards), while the rest of the page uses "screen" coordinates (origin at top-left, y increasing as you move downwards). (Actually it's more complicated; see the section on "Relationships among coordinate spaces" etc.)

But for italics, it may start with something like:

```
1 0 0.25 -1 274.297 941 Tm
```

(note the `0.25` instead of `0`), which means 

```
x' = x + 0.25y + 274.297
y' = 941 - y
```

so the `x` position increases from bottom to top of the glyph (i.e. slanting right).

----

So we'd need to keep track of the text matrix as we go; pretty much like a PDF viewer/renderer.

**Comment by shreevatsa** [comment]
As mentioned in the two commits above and [email](https://groups.google.com/g/sanskrit-programmers/c/oXRogFHeMgs/m/cYgJ48fcBAAJ), let me know if the current hack can work for this use-case. It produces a PDF on which `pdftotext` produces super-ugly output like:

> [ATMSNB+NotoSansDevanagari]आस्तीककी इस मनोरम कथाको मैं पूणर्\<CCprec>रूपसे सुनना चाहता हूँ  [/ATMSNB+NotoSansDevanagari][ATMSNB+NotoSansDevanagari]। [/ATMSNB+NotoSansDevanagari][ATMSNB+NotoSansDevanagari]। [/ATMSNB+NotoSansDevanagari][ATMSNB+NotoSansDevanagari] ५[/ATMSNB+NotoSansDevanagari] [ATMSNB+NotoSansDevanagari]  [/ATMSNB+NotoSansDevanagari][ATMSNB+NotoSansDevanagari]। [/ATMSNB+NotoSansDevanagari][ATMSNB+NotoSansDevanagari]।[/ATMSNB+NotoSansDevanagari]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [sl][ATMSNB+NotoSansDevanagari]सौि\<CCsucc>तरुवाच[/ATMSNB+NotoSansDevanagari][/sl]
                                                                                                                                                   [APZKLW+NotoSansDevanagari-Bold]इि\<CCsucc>तहासि\<CCsucc>ममं ि\<CCsucc>वप्राः पुराणं पि\<CCsucc>रचक्षते  [/APZKLW+NotoSansDevanagari-Bold][APZKLW+NotoSansDevanagari-Bold]। [/APZKLW+NotoSansDevanagari-Bold][APZKLW+NotoSansDevanagari-Bold]। [/APZKLW+NotoSansDevanagari-Bold][APZKLW+NotoSansDevanagari-Bold] ६  [/APZKLW+NotoSansDevanagari-Bold][APZKLW+NotoSansDevanagari-Bold]। [/APZKLW+NotoSansDevanagari-Bold][APZKLW+NotoSansDevanagari-Bold]।[/APZKLW+NotoSansDevanagari-Bold]

but some regexes can probably handle it. Ideally, this "formatting" (the font and slant values) should probably be left to something like `pdftotext` rather than embedding into the PDF ActualText, but for now it may be ok.

**Comment by ujjvlh** [comment]
Thanks
